### ISSUE TITLE
Allow optional `ts-mocha`

### ISSUE THREAD

**Issue by nickgartmann** [rogeliog/jest-runner-mocha#17]
By adding [ts-mocha](https://www.npmjs.com/package/ts-mocha) as a dependency and adding `require('ts-mocha')` to the top of [runMocha.js](https://github.com/rogeliog/jest-runner-mocha/blob/master/src/runMocha.js) it is possible to enable typescript mocha tests with Jest. 

However, this solution forces typescript. Hoping you can advise on how to structure a change to add an optional configuration for enabling typescript. The tricky bit is that the `require('ts-mocha')` must come before the `require('mocha')`.

**Comment by ljharb** [comment]
I'm fine with changes that make it possible to use typescript, but not with adding any typescript-related thing to deps.

Why is typescript any different than babel, ie, babel-register etc?

**Comment by nickgartmann** [comment]
This is my bad, I got down a weird rabbit hole and missed the obvious 🙃 

Typescript support can be added through the "compiler" config option: `"compiler": "node_modules/ts-node/register"`
